/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.Interfaz;

import edu.cuc.Inventario.Copiar;
import edu.cuc.Inventario.Inventario;
import edu.cuc.Inventario.Moneda;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class NuevaMoneda extends javax.swing.JDialog {

    /**
     * Creates new form busqueda
     */
    Inventario m;
    String ruta;
    ObjectOutputStream salida;
    ArrayList<Moneda> monedas;
    static int posicion;

    public NuevaMoneda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        ruta = "src/edu/cuc/Datos/datos.txt";
        m = new Inventario();

        //Cargar Tabla
        monedas = m.traermoneda(ruta);

        try {
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        m.volcado(salida, monedas);
        m.llenarMonedas(tblMonedas, monedas);
        posicion = -1;
                    txtValor.setEnabled(false);
                    txtCeca.setEnabled(false);
                    txtPais.setEnabled(false);
                    txtPeso.setEnabled(false);
                    txtAño.setEnabled(false);
                    txtTipodeMetal.setEnabled(false);
                    txtError.setEnabled(false);
                    cmbEstado.setEnabled(false);
                    taNota.setEnabled(false);
                    taCaracteristicas.setEnabled(false);
                    cmbRareza.setEnabled(false);
                    txtPrecioCompra.setEnabled(false);
                    txtPrecioDeVenta.setEnabled(false);
                    txtCodigo.setEnabled(false);
                    txtUbicacion.setEnabled(false);
                    cmbVendida.setEnabled(false);
                   

    }

    public static int getPosicion() {
        return posicion;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonedas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCeca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTipodeMetal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioDeVenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNota = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbVendida = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregarFoto = new javax.swing.JButton();
        txtUbicacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taCaracteristicas = new javax.swing.JTextArea();
        cmbRareza = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnMostrarImagenes = new javax.swing.JButton();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(992, 689));
        setMinimumSize(new java.awt.Dimension(992, 689));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMonedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Valor y Unidad         ", "Caracteriscas          ", "Ceca                     ", "Pais", "Peso                    ", "Año                    ", "Tipo de Metal        ", "Estado                  ", "Rareza                  ", "Precio de Compra", "Precio de venta", "Codigo", "Ubicacion", "Nota", "Error", "vendida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonedasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonedas);

        jLabel1.setText("Valor:");

        txtValor.setText(" ");

        jLabel2.setText("Ceca");

        jLabel3.setText("Peso:");

        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });

        jLabel4.setText("Año:");

        jLabel5.setText("Tipo de Metal: ");

        jLabel6.setText("Rareza:");

        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyTyped(evt);
            }
        });

        jLabel7.setText("Precio de Compra:");

        jLabel8.setText("Precio de venta:");

        txtPrecioDeVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioDeVentaKeyTyped(evt);
            }
        });

        jLabel9.setText("Codigo");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        jLabel10.setText("Ubicacion");

        jLabel11.setText("Nota:");

        taNota.setColumns(20);
        taNota.setRows(5);
        jScrollPane2.setViewportView(taNota);

        jLabel12.setText("Error:");

        jLabel13.setText("Vendida:");

        cmbVendida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----", "No", "Si" }));

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.setEnabled(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregarFoto.setText("Agregar foto");
        btnAgregarFoto.setEnabled(false);
        btnAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFotoActionPerformed(evt);
            }
        });

        jLabel14.setText("Caracteristicas");

        taCaracteristicas.setColumns(20);
        taCaracteristicas.setRows(5);
        jScrollPane3.setViewportView(taCaracteristicas);

        cmbRareza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------------", "muy comun", "comun", "poco comun", "rara", "muy rara" }));

        jLabel15.setText("Estado ");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------------", "Mala", "Regular", "Buena", "Excelente" }));

        jLabel16.setText("País: ");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnMostrarImagenes.setText("Mostrar Imagenes");
        btnMostrarImagenes.setEnabled(false);
        btnMostrarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarImagenesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(cmbRareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(txtCeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21)
                        .addComponent(txtPrecioDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(17, 17, 17)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(txtTipodeMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addGap(14, 14, 14)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(14, 14, 14)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addGap(8, 8, 8)
                        .addComponent(cmbVendida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo)
                            .addComponent(btnGuardar)
                            .addComponent(btnAgregarFoto)
                            .addComponent(btnBorrar)
                            .addComponent(btnModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarImagenes)))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cmbRareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtPrecioDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtTipodeMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(cmbVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnNuevo)
                        .addGap(7, 7, 7)
                        .addComponent(btnGuardar)
                        .addGap(7, 7, 7)
                        .addComponent(btnAgregarFoto)
                        .addGap(7, 7, 7)
                        .addComponent(btnBorrar)
                        .addGap(7, 7, 7)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarImagenes))
                    .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1041, 678));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

            String valor = txtValor.getText().trim();
            String ceca = txtCeca.getText().trim();
            String pais = txtPais.getText().trim();
            double peso = m.ConvertirStringADouble(txtPeso);
            String año = txtAño.getText().trim();
            String tipoDeMetal = txtTipodeMetal.getText().trim();
            String error = txtError.getText().trim();
            String nota = taNota.getText();
            String caracteristica = taCaracteristicas.getText();
            String rareza = cmbRareza.getSelectedItem().toString();
            int precioCompra = m.convertirStringAInt(txtPrecioCompra);
            double codigo = m.ConvertirStringADouble(txtCodigo);
            String ubicacion = txtUbicacion.getText().trim();
            String estado = cmbEstado.getSelectedItem().toString();
            boolean vendida = m.traducirSiNo(cmbVendida.getSelectedItem().toString());
            if (peso == -1) {
                JOptionPane.showMessageDialog(this, "El peso no puede estar vacio");
            }
            if (codigo == -1) {
                JOptionPane.showMessageDialog(this, "El codigo no puede estar vacio");
            }
            if (m.validarCodigo(ruta, codigo)) {
                JOptionPane.showMessageDialog(this, "Este codigo ya esta registrado, por favor ingrese uno diferente.");
            }else{
            Moneda mon;

            mon = new Moneda(valor, caracteristica, ceca, ubicacion, peso, año, tipoDeMetal, estado, rareza, precioCompra, codigo, ubicacion, nota, error, vendida);

            mon.guardar(salida);
            monedas = m.traermoneda(ruta);
            m.llenarMonedas(tblMonedas, monedas);
            txtValor.setText("");
            txtCeca.setText("");
            txtPais.setText("");
            txtPeso.setText("");
            txtAño.setText("");
            txtTipodeMetal.setText("");
            txtError.setText("");
            cmbEstado.setSelectedItem("--------------");
            taNota.setText("");
            taCaracteristicas.setText("");
            cmbRareza.setSelectedItem("--------------");
            txtPrecioCompra.setText("");
            txtPrecioDeVenta.setText("");
            txtCodigo.setText("");
            txtUbicacion.setText("");
            cmbVendida.setSelectedItem("");

            posicion = -1;
            
            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnBorrar.setEnabled(false);
            btnAgregarFoto.setEnabled(false);
             btnMostrarImagenes.setEnabled(false);
            

                    txtValor.setEnabled(false);
                    txtCeca.setEnabled(false);
                    txtPais.setEnabled(false);
                    txtPeso.setEnabled(false);
                    txtAño.setEnabled(false);
                    txtTipodeMetal.setEnabled(false);
                    txtError.setEnabled(false);
                    cmbEstado.setEnabled(false);
                    taNota.setEnabled(false);
                    taCaracteristicas.setEnabled(false);
                    cmbRareza.setEnabled(false);
                    txtPrecioCompra.setEnabled(false);
                    txtPrecioDeVenta.setEnabled(false);
                    txtCodigo.setEnabled(false);
                    txtUbicacion.setEnabled(false);
                    cmbVendida.setEnabled(false);
            btnNuevo.setText("Nuevo");
            } } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblMonedasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonedasMouseClicked
        // TODO add your handling code here:
        posicion = tblMonedas.getSelectedRow();
        monedas = m.traermoneda(ruta);
        txtValor.setText(monedas.get(posicion).getValorYUnidad());
        txtCeca.setText(monedas.get(posicion).getCeca());
        txtPais.setText(monedas.get(posicion).getPaisDeCreacion());
        txtPeso.setText(monedas.get(posicion).getPeso() + "");
        txtAño.setText(monedas.get(posicion).getAño());
        txtTipodeMetal.setText(monedas.get(posicion).getTipoDeMetal());
        txtError.setText(monedas.get(posicion).getError());
        cmbEstado.setSelectedItem(monedas.get(posicion).getEstado());
        taNota.setText(monedas.get(posicion).getNota());
        taCaracteristicas.setText(monedas.get(posicion).getCaracteristicas());
        cmbRareza.setSelectedItem(monedas.get(posicion).getRareza());
        txtPrecioCompra.setText(monedas.get(posicion).getPrecioDeCompra() + "");
        txtPrecioDeVenta.setText(monedas.get(posicion).getPrecioDeVenta() + "");
        txtCodigo.setText(monedas.get(posicion).getCodigo() + "");
        txtUbicacion.setText(monedas.get(posicion).getUbicacion());
        cmbVendida.setSelectedItem(monedas.get(posicion).isVendida());
        
//        if (monedas.get(posicion).getFotos().isEmpty()) {
//            System.out.println("no hay fotos");
//        }else{
//        if (monedas.get(posicion).getFotos().get(0)!=null) {
//            ImageIcon imagen= monedas.get(posicion).getFotos().get(0);
//             Imagen.setIcon(imagen);
//             System.out.println(imagen);
//        }}
        
                    txtValor.setEnabled(true);
                    txtCeca.setEnabled(true);
                    txtPais.setEnabled(true);
                    txtPeso.setEnabled(true);
                    txtAño.setEnabled(true);
                    txtTipodeMetal.setEnabled(true);
                    txtError.setEnabled(true);
                    cmbEstado.setEnabled(true);
                    taNota.setEnabled(true);
                    taCaracteristicas.setEnabled(true);
                    cmbRareza.setEnabled(true);
                    txtPrecioCompra.setEnabled(true);
                    txtPrecioDeVenta.setEnabled(true);
                    txtCodigo.setEnabled(false);
                    txtUbicacion.setEnabled(true);
                    cmbVendida.setEnabled(true);
        
        
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnAgregarFoto.setEnabled(true);
        btnMostrarImagenes.setEnabled(true);

        btnNuevo.setText("Cancelar");
    }//GEN-LAST:event_tblMonedasMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        try {
            if (monedas.isEmpty() || posicion > monedas.size() || posicion < 0) {
                JOptionPane.showMessageDialog(this, "no hay ninguna moneda  seleccionada");
            } else {
                int opcion;
                opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro de Borrar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
                try {
                    m.borrarDato(opcion, posicion, ruta, ruta, tblMonedas, salida);
                    txtValor.setText("");
                    txtCeca.setText("");
                    txtPais.setText("");
                    txtPeso.setText("");
                    txtAño.setText("");
                    txtTipodeMetal.setText("");
                    txtError.setText("");
                    cmbEstado.setSelectedItem("--------------");
                    taNota.setText("");
                    taCaracteristicas.setText("");
                    cmbRareza.setSelectedItem("--------------");
                    txtPrecioCompra.setText("");
                    txtPrecioDeVenta.setText("");
                    txtCodigo.setText("");
                    txtUbicacion.setText("");
                    cmbVendida.setSelectedItem("");
                    posicion = -1;
                    System.out.println(posicion);
                                btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnBorrar.setEnabled(false);
            btnAgregarFoto.setEnabled(false);
            btnMostrarImagenes.setEnabled(false);
            

                    txtValor.setEnabled(false);
                    txtCeca.setEnabled(false);
                    txtPais.setEnabled(false);
                    txtPeso.setEnabled(false);
                    txtAño.setEnabled(false);
                    txtTipodeMetal.setEnabled(false);
                    txtError.setEnabled(false);
                    cmbEstado.setEnabled(false);
                    taNota.setEnabled(false);
                    taCaracteristicas.setEnabled(false);
                    cmbRareza.setEnabled(false);
                    txtPrecioCompra.setEnabled(false);
                    txtPrecioDeVenta.setEnabled(false);
                    txtCodigo.setEnabled(false);
                    txtUbicacion.setEnabled(false);
                    cmbVendida.setEnabled(false);
            btnNuevo.setText("Nuevo");
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                }

            }
        } catch (ArrayIndexOutOfBoundsException arrayIndexOutOfBoundsException) {
            JOptionPane.showMessageDialog(this, "No hay ninguna moneda seleccionada");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFotoActionPerformed
        // TODO add your handling code here:
        if (monedas.isEmpty() || posicion > monedas.size() || posicion < 0) {
            JOptionPane.showMessageDialog(this, "no hay ninguna moneda seleccionada");
        } else {
            try {
                Moneda mon = monedas.get(posicion);
                Copiar imagenes = new Copiar();
                ImageIcon imagenGuardada = imagenes.getImagen();
                mon.agregarFoto(imagenGuardada);
                
                try {
                    salida = new ObjectOutputStream(new FileOutputStream(ruta));
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
//                mon.guardar(salida);
                //Paso 5
                m.volcado(salida, monedas);
//
//                //Paso 6
//                m.llenarMonedas(tblMonedas, monedas);
//                Imagen.setIcon(mon.getFotos().get(0));
//                System.out.println(m.traermoneda(ruta));
            System.out.println(mon.getFotos());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_btnAgregarFotoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
                if(btnNuevo.getText().equals("Nuevo")){    
        
                    txtValor.setText("");
                    txtCeca.setText("");
                    txtPais.setText("");
                    txtPeso.setText("");
                    txtAño.setText("");
                    txtTipodeMetal.setText("");
                    txtError.setText("");
                    cmbEstado.setSelectedItem("--------------");
                    taNota.setText("");
                    taCaracteristicas.setText("");
                    cmbRareza.setSelectedItem("--------------");
                    txtPrecioCompra.setText("");
                    txtPrecioDeVenta.setText("");
                    txtCodigo.setText("");
                    txtUbicacion.setText("");
                    cmbVendida.setSelectedItem("");
                    posicion = -1;
            
        
            
            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnBorrar.setEnabled(false);
            btnAgregarFoto.setEnabled(false);
            btnMostrarImagenes.setEnabled(false);
            
                    txtValor.setEnabled(true);
                    txtCeca.setEnabled(true);
                    txtPais.setEnabled(true);
                    txtPeso.setEnabled(true);
                    txtAño.setEnabled(true);
                    txtTipodeMetal.setEnabled(true);
                    txtError.setEnabled(true);
                    cmbEstado.setEnabled(true);
                    taNota.setEnabled(true);
                    taCaracteristicas.setEnabled(true);
                    cmbRareza.setEnabled(true);
                    txtPrecioCompra.setEnabled(true);
                    txtPrecioDeVenta.setEnabled(true);
                    txtCodigo.setEnabled(true);
                    txtUbicacion.setEnabled(true);
                    cmbVendida.setEnabled(true);
            
            btnNuevo.setText("Cancelar");
        }else{
                    txtValor.setText("");
                    txtCeca.setText("");
                    txtPais.setText("");
                    txtPeso.setText("");
                    txtAño.setText("");
                    txtTipodeMetal.setText("");
                    txtError.setText("");
                    cmbEstado.setSelectedItem("--------------");
                    taNota.setText("");
                    taCaracteristicas.setText("");
                    cmbRareza.setSelectedItem("--------------");
                    txtPrecioCompra.setText("");
                    txtPrecioDeVenta.setText("");
                    txtCodigo.setText("");
                    txtUbicacion.setText("");
                    cmbVendida.setSelectedItem("");
                    posicion = -1;
            
            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnBorrar.setEnabled(false);
            btnAgregarFoto.setEnabled(false);
            btnMostrarImagenes.setEnabled(false);
            
                    txtValor.setEnabled(false);
                    txtCeca.setEnabled(false);
                    txtPais.setEnabled(false);
                    txtPeso.setEnabled(false);
                    txtAño.setEnabled(false);
                    txtTipodeMetal.setEnabled(false);
                    txtError.setEnabled(false);
                    cmbEstado.setEnabled(false);
                    taNota.setEnabled(false);
                    taCaracteristicas.setEnabled(false);
                    cmbRareza.setEnabled(false);
                    txtPrecioCompra.setEnabled(false);
                    txtPrecioDeVenta.setEnabled(false);
                    txtCodigo.setEnabled(false);
                    txtUbicacion.setEnabled(false);
                    cmbVendida.setEnabled(false);

            
            btnNuevo.setText("Nuevo");
        } 
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {                                             
            // TODO add your handling code here:
            
            //Paso 1
            monedas = m.traermoneda(ruta);
            
            //Paso 2
            posicion=tblMonedas.getSelectedRow();
            
            //Paso 3
            Moneda moneda= monedas.get(posicion);
            moneda.setValorYUnidad(txtValor.getText().trim());
            moneda.setCeca(txtCeca.getText().trim());
            moneda.setPaisDeCreacion(txtPais.getText().trim());
            moneda.setPeso(m.ConvertirStringADouble(txtPeso));
            moneda.setAño(txtAño.getText().trim());
            moneda.setTipoDeMetal(txtTipodeMetal.getText().trim());
            moneda.setError(txtError.getText().trim());
            moneda.setEstado(cmbEstado.getSelectedItem().toString());
            moneda.setNota(taNota.getText().trim());
            moneda.setCaracteristicas(taCaracteristicas.getText().trim());
            moneda.setRareza(cmbRareza.getSelectedItem().toString());
            moneda.setPrecioDeCompra(m.convertirStringAInt(txtPrecioCompra));
            if (m.traducirSiNo(cmbVendida.getSelectedItem().toString())) {
            }else{
            moneda.setPrecioDeVenta(0);
            }

            moneda.setUbicacion(txtUbicacion.getText().trim());
            moneda.setVendida(m.traducirSiNo(cmbVendida.getSelectedItem().toString()));
            
            //Paso 4
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            //Paso 5
            m.volcado(salida, monedas);
            monedas= m.traermoneda(ruta);
            //Paso 6
            m.llenarMonedas(tblMonedas, monedas);
            
            JOptionPane.showMessageDialog(this, "Persona modificada exitosamente!!");
            
                    txtValor.setText("");
                    txtCeca.setText("");
                    txtPais.setText("");
                    txtPeso.setText("");
                    txtAño.setText("");
                    txtTipodeMetal.setText("");
                    txtError.setText("");
                    cmbEstado.setSelectedItem("--------------");
                    taNota.setText("");
                    taCaracteristicas.setText("");
                    cmbRareza.setSelectedItem("--------------");
                    txtPrecioCompra.setText("");
                    txtPrecioDeVenta.setText("");
                    txtCodigo.setText("");
                    txtUbicacion.setText("");
                    cmbVendida.setSelectedItem("");
                    posicion = -1;
            
            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnBorrar.setEnabled(false);
            btnAgregarFoto.setEnabled(false);
            btnMostrarImagenes.setEnabled(false);
            
                    txtValor.setEnabled(false);
                    txtCeca.setEnabled(false);
                    txtPais.setEnabled(false);
                    txtPeso.setEnabled(false);
                    txtAño.setEnabled(false);
                    txtTipodeMetal.setEnabled(false);
                    txtError.setEnabled(false);
                    cmbEstado.setEnabled(false);
                    taNota.setEnabled(false);
                    taCaracteristicas.setEnabled(false);
                    cmbRareza.setEnabled(false);
                    txtPrecioCompra.setEnabled(false);
                    txtPrecioDeVenta.setEnabled(false);
                    txtCodigo.setEnabled(false);
                    txtUbicacion.setEnabled(false);
                    cmbVendida.setEnabled(false);
            
            btnNuevo.setText("Nuevo");
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnMostrarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarImagenesActionPerformed
        // TODO add your handling code here:
        if (!monedas.get(posicion).getFotos().isEmpty()) {
                 MostrarImagenes MI = new MostrarImagenes(null, true);
        MI.setVisible(true);   
        }else{
        JOptionPane.showMessageDialog(this, "No hay imagenes de esta moneda.");
        }

    }//GEN-LAST:event_btnMostrarImagenesActionPerformed

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && c != '.') {
            evt.consume();
        }
        if (txtPeso.getText().contains(".") && (c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPesoKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
                        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && c != '.') {
            evt.consume();
        }
        if (txtCodigo.getText().contains(".") && (c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioCompraKeyTyped

    private void txtPrecioDeVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioDeVentaKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioDeVentaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaMoneda dialog = new NuevaMoneda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFoto;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarImagenes;
    private javax.swing.JButton btnNuevo;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbRareza;
    private javax.swing.JComboBox cmbVendida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taCaracteristicas;
    private javax.swing.JTextArea taNota;
    private javax.swing.JTable tblMonedas;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCeca;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioDeVenta;
    private javax.swing.JTextField txtTipodeMetal;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
